name: Release
on:
  push:
    tags-ignore:
      - '**'
    workflow_dispatch:

jobs:
  test: # Here we need to consider whether we need to ensure that the test passes before releasing
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        go: ['1.17', '1.18', '1.19']
    name: Go ${{ matrix.go }} test
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Unit test
        run: make
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: coverage.html
          path: /tmp/coverage.html
      - uses: actions/upload-artifact@v1
        with:
          name: coverage.html
          path: /tmp/coverage.html
#      - run: go test -race -v -coverprofile=profile.cov ./pkg/...
#      - uses: codecov/codecov-action@v3.1.1
#        with:
#          file: ./profile.cov
#          name: codecov-go
  release:
    runs-on: ubuntu-22.04
    needs: [test]
#    if: ${{ github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main' }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Source checkout
        uses: actions/checkout@v3
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          dry_run: false
          semantic_version: 18.0.1
          extra_plugins: |
            @semantic-release/exec@6.0.3